import Instagram from '@/assets/svg/instagram.svg'
import TikTok from '@/assets/svg/tiktok.svg'
import type { Person } from '@/types/people'
import { calculateAge } from '@/utils/calc-age'

export const PEOPLE: Person[] = [
	// TERESA
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'Palabra clave: Altruista\nGrado de postureo: 2/10 (si puede no aparece, por eso siempre sale en movimiento).\nCompañera del Toby a tiempo completo, funcionaria a tiempo parcial. Le encanta viajar aunque le dan miedo los aviones, le encantan los parques de atracciones... y sí, le dan miedo las atracciones. En sus contradicciones está su esencia. Dale dos cervezas y conocerás a su versión desenfrenada ¿Estás preparada?\nAdvertencia: Encontrar un restaurante en el que pueda comer es complicado, ya que no come nada con OJOS.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1995, 9, 2),
		age: calculateAge(new Date(1995, 9, 2)),
		city: 'Tobarra',
		drink: 'Daiquiri de fresita',
		pub: 'En mi cama con el Toby',
		song: 'Auxiliar de Amaia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@ajsofjfpme',
				label: 'Visitar perfil de Teresa en TikTok',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
		],
	},
	// CARLOS
	{
		id: 'carlos',
		name: 'Carlos',
		bio: 'Palabra clave: Complicidad\nGrado de postureo: 7/10 (sube si está tranquilo, baja si hay fiesta).\nAlgunos lo conocen como Mike, todos lo conocen por su habilidad para conseguir una cerveza en cualquier situación.\nAdvertencia: se pierde con facilidad. No dejar sin supervisión.',
		realName: 'Carlos Izquierdo (Mike)',
		birthDate: new Date(1995, 2, 28),
		age: calculateAge(new Date(1995, 2, 28)),
		city: 'Tobarra',
		drink: 'Zumo de melocotón',
		pub: 'En Temper',
		song: 'Canción favorita',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/carlosizqmike',
				label: 'Visitar perfil de Carlos en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@ajsofjfpme',
			// 	label: 'Visitar perfil de Carlos en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Carlos en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// ESTHER
	{
		id: 'esther',
		name: 'Esther',
		bio: 'Palabra clave: Refugio\nGrado de postureo: 9/10 (aunque el bronceador a veces tenga otros planes).\nAmante del postureo y cazadora oficial de la foto perfecta. Ha dejado atrás los bocadillos de cangrejo del recreo para convertirse en chef de platos ricos y 100% instagrameables.\nHacerla feliz es fácil: una cervecita, unas tapas y un buen rato de cotilleo y dramas ajenos (que si son propios, también se comentan).',
		realName: 'Esther Alfaro',
		birthDate: new Date(1995, 7, 25),
		age: calculateAge(new Date(1995, 7, 25)),
		city: 'Tobarra',
		drink: 'zumo de naranja',
		pub: 'no podría perderme en ningún sitio, lo subiría siempre a instagram',
		song: 'Saharabbey Road de Vetusta Morla',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/estherkichu',
				label: 'Visitar perfil de Esther en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/',
			// 	label: 'Visitar perfil de Esther en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Esther en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// MARIU
	{
		id: 'mariu',
		name: 'Mariu',
		bio: 'Palabra clave: Energía\nGrado de postureo: 8/10\nSiempre se implica con todo y todos, le encantan las cervecitas en el Babi y los buenos salseos. Se le ha visto adoptar la forma de Cassandra en sus momentos de ira.\nAdvertencia: vigilar de cerca si hace el baile de Anita, puede acabar con chicles pegados en el pelo.',
		realName: 'María Eugenia',
		birthDate: new Date(1995, 10, 19),
		age: calculateAge(new Date(1995, 10, 19)),
		city: 'Tobarra',
		drink: 'Estrella Levante fresquita',
		pub: 'en el escenario de ellyelladjs',
		song: 'Envolver',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/marieuropa',
				label: 'Visitar perfil de Mariu en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@ajsofjfpme',
			// 	label: 'Visitar perfil de Mariu en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Mariu en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// VALENTIN
	{
		id: 'valen',
		name: 'Valentín',
		bio: 'Palabra clave: FOMO\nGrado de postureo: 7/10 (Mejor no le hagas fotos pasadas las 3PM).\nSe apunta a todos los planes: festis, fiestas de pueblo, bodas… lo que haya. Y si hay que quedarse hasta el final, él se queda, e increíblemente siempre encuentra a alguien. La cervecita es su debilidad, y en Tobarra ha encontrado su lugar en el mundo.\nAdvertencia: no dejar invitar a chupitos, copas o cervezas. Su tarjeta pide AYUD.',
		realName: 'Valentín Lorente',
		birthDate: new Date(1994, 7, 21),
		age: calculateAge(new Date(1994, 7, 21)),
		city: 'Ceutí',
		drink: 'Una Cerveza Cualquiera',
		pub: 'En el PC',
		song: 'Kerosene - Crystal Castles',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/vlorente',
				label: 'Visitar perfil de Valentín en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@vlorente',
				label: 'Visitar perfil de Valentín en TikTok',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
		],
	},
	// VICKY
	{
		id: 'vicky',
		name: 'Vicky',
		bio: 'Palabra clave: Soñadora\nGrado de postureo: 8/10 (sus mejores fotos siempre salen en conciertos, con la sonrisa al máximo)\nQuiere viajar por el mundo, aunque es complicado pillar vuelos desde la Luna. Hacerla reír es fácil, pero cuidado: si lo consigues, prepárate para un bucle infinito de risas contagiosas (y no es tópico, es real).\nCuidado, se atreve a todo, no le propongas cosas de las que te puedas arrepentir.',
		realName: 'Victoria',
		birthDate: new Date(1995, 2, 4),
		age: calculateAge(new Date(1995, 2, 4)),
		city: 'Tobarra',
		drink: 'Freeway',
		pub: 'La Luna',
		song: 'Alguna de K-POP',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/vikrokosmos',
				label: 'Visitar perfil de Vicky en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Vicky en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Vicky en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// MAJO
	{
		id: 'majo',
		name: 'Majo',
		bio: 'Palabra clave: Encanto\nGrado de postureo: 9/10 (siempre lista para vestirse de guapa)\nPuedes contar con ella en los buenos y malos momentos; siempre estará ahí para ayudarte. El tinto siempre le entra bien, y más si estamos juntos; mejora aún más si es en un destino paradisiaco, pero le vale un bar de Juan.\nAdvertencia: NO enfadar, aunque no lo parezca tiene genio.',
		realName: 'María José Jiménez',
		birthDate: new Date(1995, 5, 22),
		age: calculateAge(new Date(1995, 5, 22)),
		city: 'Tobarra',
		drink: 'Mojito',
		pub: 'Maldivas',
		song: 'El fin del mundo',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/mariajose.jimenezg',
				label: 'Visitar perfil de Majo en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Majo en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Majo en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// ADRIAN
	{
		id: 'adrian',
		name: 'Adrián',
		bio: 'Palabra clave: Explorador\nGrado de postureo: 5/10 (ha tenido que mejorar desde que está con su novia)\nEs la persona que más gente conoce en el mundo; podría reducir a la mitad la teoría de los 6 grados de separación. Siempre está dispuesto a disfrutar de todo y hacer que la gente sienta lo mismo.\nNo confundir con su perro Milú: aunque lo parezca no comparten sangre.',
		realName: 'Adrían Rodriguez',
		birthDate: new Date(1994, 3, 3),
		age: calculateAge(new Date(1994, 3, 3)),
		city: 'Murcianico',
		drink: 'La Cerveza',
		pub: 'en la montaña',
		song: 'Asuntos Serios de El puchero del hortelano',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/adrirm.94',
				label: 'Visitar perfil de Adrián en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Adrián en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Adrián en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// MARIA
	{
		id: 'maria',
		name: 'María',
		bio: 'Palabra clave: Gozadora\nGrado de postureo: 8/10 (una buena selfie le encanta)\nPuedes encontrártela cantando a viva voz en el coche; no te asustes, es su manera de desestresarse. Le encanta una buena cervecita, ya sea en un bar, un chiringuito o en casa, y si viene con compañía, mejor aún.\nAdvertencia: no le recuerdes la época de Disney Channel, podría obligarte a ver Camp Rock una y otra vez.',
		realName: 'María López',
		birthDate: new Date(1995, 6, 14),
		age: calculateAge(new Date(1995, 6, 14)),
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Go Global',
		song: 'N/A',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/marialopnav',
				label: 'Visitar perfil de María en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de María en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de María en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// EU
	{
		id: 'eu',
		name: 'Eu',
		bio: 'Palabra clave: Chill\nGrado de postureo: 6/10 (es más de dejarse llevar)\nSiempre te va a sacar una sonrisa, aunque solo sea porque su felicidad se contagia. Dale una botellita de agua y te animará toda la noche como si fuera tequila.\nAdvertencia: no le dejéis volver a disfrazarse de plátano. Por favor, no más.',
		realName: 'Eustaquio Cascales',
		birthDate: new Date(1994, 5, 17),
		age: calculateAge(new Date(1994, 5, 17)),
		city: 'Ceutí',
		drink: 'Aguita Mineral',
		pub: 'Mazarrón',
		song: 'N/A',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/eucascales',
				label: 'Visitar perfil de Eu en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Eu en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Eu en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// FATIMA
	{
		id: 'fatima',
		name: 'Fátima',
		bio: 'Palabra clave: Detallista\nGrado de postureo: 9/10 (ser la reina de las fiestas requiere mucho esfuerzo y sacrificio).\nSiempre implicada con todo, aunque su apretada agenda no siempre lo ponga fácil Si consigues cuadrar un plan con ella, disfrutarás de su alegría y energía, que no es poca (que no es poca… recorrerse Disney varias veces no es cualquier cosa). Dejó atrás sus grandes borracheras… aunque un desliz lo puede tener cualquiera.\nAdvertencia: NO permitir que pida chupitos. Luego solo queda ella de pie, y tú preguntándote qué ha pasado.',
		realName: 'Fátima Paterna',
		birthDate: new Date(1995, 7, 13),
		age: calculateAge(new Date(1995, 7, 13)),
		city: 'Tobarra',
		drink: 'Agua Mineral',
		pub: 'En Disney',
		song: 'N/A',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/fatimapaterna',
				label: 'Visitar perfil de Fátima en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Fátima en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Fátima en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// RAFA
	{
		id: 'rafa',
		name: 'Rafa',
		bio: 'Palabra clave: Pasión\nGrado de postureo 9/10 (salir mal en una foto no entra en sus planes).\nVive todo al máximo: lo bueno, lo malo, lo caótico… Con él, la vida siempre tiene un extra de intensidad. Aunque esté lejos, nunca falta una historia suya que contar. Y si se le puede llamar para que la escenifique, mejor aún.\nAdvertencia: no dejarlo solo en la noche. Siempre vuelve… pero con gente nueva.',
		realName: 'Rafael Pastor',
		birthDate: new Date(1995, 5, 24),
		age: calculateAge(new Date(1995, 5, 24)),
		city: 'Cork',
		drink: 'Líquido de alta graduación',
		pub: 'En Cork',
		song: 'N/A',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/rafiichi',
				label: 'Visitar perfil de Rafa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Rafa en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Rafa en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
	// ROCIO
	{
		id: 'rocio',
		name: 'Rocío',
		bio: 'Palabra clave: Chispa\nGrado de postureo: 8/10 (le gusta salir bien, pero prefiere un buen tiktok)\nSiempre con una sonrisa, tiene el poder de hacer reír a cualquiera. Se adapta a todos los planes: si es tranquilo, te transmite paz; si es de fiesta… buena suerte siguiéndole el ritmo. Dale un poco de cariño y te lo devuelve multiplicado por diez.\nAdvertencia: no acercar a hombres motorizados ni uniformados.',
		realName: 'Rocío Pinar',
		birthDate: new Date(1995, 0, 30),
		age: calculateAge(new Date(1995, 0, 30)),
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'En La Tarima',
		song: 'N/A',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/rociopima',
				label: 'Visitar perfil de Rocío en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			// {
			// 	id: 'tiktok',
			// 	name: 'TikTok',
			// 	url: 'https://www.tiktok.com/@',
			// 	label: 'Visitar perfil de Rocío en TikTok',
			// 	image: {
			// 		logo: TikTok,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
			// {
			// 	id: 'x',
			// 	name: 'X',
			// 	url: 'https://x.com/',
			// 	label: 'Visitar perfil de Rocío en X',
			// 	image: {
			// 		logo: X,
			// 		width: 200,
			// 		height: 200,
			// 	},
			// },
		],
	},
] as const
