import Instagram from '@/assets/svg/instagram.svg'
import TikTok from '@/assets/svg/tiktok.svg'
import X from '@/assets/svg/x.svg'
import type { Person } from '@/types/people'

export const PEOPLE: Person[] = [
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1998, 11, 21),
		age: 29,
		gallery: true,
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Babilonia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@peereira7',
				label: 'Visitar perfil de Peereira en TikTok',
				followers: '585k',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'x',
				name: 'X',
				url: 'https://x.com/Peereira7',
				label: 'Visitar perfil de Peereira en X',
				followers: '310k',
				image: {
					logo: X,
					width: 200,
					height: 200,
				},
			},
		],
	},
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1998, 11, 21),
		age: 29,
		gallery: true,
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Babilonia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@peereira7',
				label: 'Visitar perfil de Peereira en TikTok',
				followers: '585k',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'x',
				name: 'X',
				url: 'https://x.com/Peereira7',
				label: 'Visitar perfil de Peereira en X',
				followers: '310k',
				image: {
					logo: X,
					width: 200,
					height: 200,
				},
			},
		],
	},
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1998, 11, 21),
		age: 29,
		gallery: true,
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Babilonia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@peereira7',
				label: 'Visitar perfil de Peereira en TikTok',
				followers: '585k',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'x',
				name: 'X',
				url: 'https://x.com/Peereira7',
				label: 'Visitar perfil de Peereira en X',
				followers: '310k',
				image: {
					logo: X,
					width: 200,
					height: 200,
				},
			},
		],
	},
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1998, 11, 21),
		age: 29,
		gallery: true,
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Babilonia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@peereira7',
				label: 'Visitar perfil de Peereira en TikTok',
				followers: '585k',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'x',
				name: 'X',
				url: 'https://x.com/Peereira7',
				label: 'Visitar perfil de Peereira en X',
				followers: '310k',
				image: {
					logo: X,
					width: 200,
					height: 200,
				},
			},
		],
	},
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1998, 11, 21),
		age: 29,
		gallery: true,
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Babilonia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@peereira7',
				label: 'Visitar perfil de Peereira en TikTok',
				followers: '585k',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'x',
				name: 'X',
				url: 'https://x.com/Peereira7',
				label: 'Visitar perfil de Peereira en X',
				followers: '310k',
				image: {
					logo: X,
					width: 200,
					height: 200,
				},
			},
		],
	},
	{
		id: 'teresa',
		name: 'Teresa',
		bio: 'El streamer español Peereira7 es un creador de contenido de eSports. Combina sus directos en videojuegos como Valorant o Fortnite con otros contenidos IRL y de viajes. Futbolero y fan del RC Deportivo de la Coruña, su nombre real es Pablo y uno de sus motes, además de Pereira, es ‘El Gorras’. 163 centímetros de mala baba, ideal para dejarlo todo en el ring.',
		realName: 'Teresa Poveda Iniesta',
		birthDate: new Date(1998, 11, 21),
		age: 29,
		gallery: true,
		city: 'Tobarra',
		drink: 'Gin Tonic',
		pub: 'Babilonia',
		socials: [
			{
				id: 'instagram',
				name: 'Instagram',
				url: 'https://www.instagram.com/teresapoved',
				label: 'Visitar perfil de Teresa en Instagram',
				image: {
					logo: Instagram,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'tiktok',
				name: 'TikTok',
				url: 'https://www.tiktok.com/@peereira7',
				label: 'Visitar perfil de Peereira en TikTok',
				followers: '585k',
				image: {
					logo: TikTok,
					width: 200,
					height: 200,
				},
			},
			{
				id: 'x',
				name: 'X',
				url: 'https://x.com/Peereira7',
				label: 'Visitar perfil de Peereira en X',
				followers: '310k',
				image: {
					logo: X,
					width: 200,
					height: 200,
				},
			},
		],
	},
] as const
